name: Extract and Commit Trial Count

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  extract-and-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run model
        id: analyse-daily-wordle
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          architecture: arm64
      - run: |
          pip install -r ./requirements.txt
          python model.py -i
          python generate_graph.py

      - name: Commit and push changes to branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add trial_count.txt assets/daily.png
          git commit -m "Update Trial Count"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
